# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

schema_version: 1

context:
  version: 0.6.0a0
  js_version: ${{ version | replace("a", "-alpha.") | replace("b", "-beta.") | replace("rc", "-rc.") }}
  jupyterlab_version: ">=4.4.0a2,<4.5"
  notebook_version: ">=7.4.0a1,<7.5"
  PYTHON: ${{ PYTHON | default("$PYTHON") }}

recipe:
  name: jupyterlite-core-split
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlite-core/jupyterlite_core-${{ version }}.tar.gz
  sha256: 9a7d75ad67e61e19e42e39c6b25b20f61ef69fe9bfb9bd2c6e263b193d9becd6

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: jupyterlite-core
    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
        - ${{ PYTHON }} ${{ RECIPE_DIR }}/extract-third-party-licenses.py
      python:
        entry_points:
          - jupyter-lite = jupyterlite_core.app:main
    requirements:
      host:
        - hatchling >=1.6.3,<2
        - pip
        - python ${{ python_min }}.*
      run:
        - doit >=0.34,<1
        - importlib-metadata >=3.6
        - jupyter_core >=4.7
        - python >=${{ python_min }}
    tests:
      - python:
          pip_check: true
          imports:
            - jupyterlite_core
      - requirements:
          run:
            - python ${{ python_min }}.*
        script: jupyter-lite --help
    about:
      summary: Tools for building JupyterLite sites
      license: BSD-3-Clause
      license_file:
        - LICENSE
        - third-party-licenses.json
      homepage: https://github.com/jupyterlite/jupyterlite
      documentation: https://jupyterlite.readthedocs.io

  - package:
      name: jupyterlite-core-with-libarchive
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("jupyterlite-core", upper_bound="x.x.x") }}
        - python-libarchive-c >=4.0
    tests:
      - python:
          pip_check: true
          imports:
            - jupyterlite_core
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - jupyter lite --help
    about:
      summary: Tools for building JupyterLite sites (with libarchive)
      license: BSD-3-Clause
      license_file:
        - LICENSE
        - third-party-licenses.json
      homepage: https://github.com/jupyterlite/jupyterlite
      documentation: https://jupyterlite.readthedocs.io

  - package:
      name: jupyterlite-core-with-lab
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("jupyterlite-core", upper_bound="x.x.x") }}
        - jupyterlab ${{ jupyterlab_version }}
        - notebook ${{ notebook_version }}
    tests:
      - python:
          pip_check: true
          imports:
            - jupyterlite_core
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - jupyter lite --help
    about:
      summary: Tools for building JupyterLite sites (with jupyterlab)
      license: BSD-3-Clause
      license_file:
        - LICENSE
        - third-party-licenses.json
      homepage: https://github.com/jupyterlite/jupyterlite
      documentation: https://jupyterlite.readthedocs.io

  - package:
      name: jupyterlite-core-with-contents
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("jupyterlite-core", upper_bound="x.x.x") }}
        - jupyter_server
    tests:
      - python:
          pip_check: true
          imports:
            - jupyterlite_core
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - jupyter lite --help
    about:
      summary: Tools for building JupyterLite sites (with contents)
      license: BSD-3-Clause
      license_file:
        - LICENSE
        - third-party-licenses.json
      homepage: https://github.com/jupyterlite/jupyterlite
      documentation: https://jupyterlite.readthedocs.io

  - package:
      name: jupyterlite-core-with-translation
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("jupyterlite-core", upper_bound="x.x.x") }}
        - jupyterlab_server >=2.8.1,<3
    tests:
      - python:
          pip_check: true
          imports:
            - jupyterlite_core
      - requirements:
          run:
            - python ${{ python_min }}.*
        script: jupyter lite --help
    about:
      summary: Tools for building JupyterLite sites (with translation)
      license: BSD-3-Clause
      license_file:
        - LICENSE
        - third-party-licenses.json
      homepage: https://github.com/jupyterlite/jupyterlite
      documentation: https://jupyterlite.readthedocs.io

  - package:
      name: jupyterlite-core-with-serve
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("jupyterlite-core", upper_bound="x.x.x") }}
        - tornado >=6.1
    tests:
      - python:
          pip_check: true
          imports:
            - jupyterlite_core
      - requirements:
          run:
            - python ${{ python_min }}.*
        script: jupyter lite --help
    about:
      summary: Tools for building JupyterLite sites (with serve)
      license: BSD-3-Clause
      license_file:
        - LICENSE
        - third-party-licenses.json
      homepage: https://github.com/jupyterlite/jupyterlite
      documentation: https://jupyterlite.readthedocs.io

  - package:
      name: jupyterlite-core-with-check
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("jupyterlite-core", upper_bound="x.x.x") }}
        - jsonschema-with-format-nongpl >=3
    tests:
      - python:
          pip_check: true
          imports:
            - jupyterlite_core
      - requirements:
          run:
            - python ${{ python_min }}.*
        script: jupyter lite --help
    about:
      summary: Tools for building JupyterLite sites (with check)
      license: BSD-3-Clause
      license_file:
        - LICENSE
        - third-party-licenses.json
      homepage: https://github.com/jupyterlite/jupyterlite
      documentation: https://jupyterlite.readthedocs.io

  - package:
      name: jupyterlite-core-with-all
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("jupyterlite-core-with-check", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("jupyterlite-core-with-contents", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("jupyterlite-core-with-lab", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("jupyterlite-core-with-libarchive", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("jupyterlite-core-with-serve", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("jupyterlite-core-with-translation", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("jupyterlite-core", upper_bound="x.x.x") }}
    tests:
      - python:
          pip_check: true
          imports:
            - jupyterlite_core
      - requirements:
          run:
            - if: linux
              then: diffoscope
            - python ${{ python_min }}.*
            - pytest-console-scripts >=1.4.0
            - pytest-cov
        script:
          - jupyter lite --help
          - pytest -vv --pyargs jupyterlite_core --script-launch-mode=subprocess --cov=jupyterlite_core --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=93
    about:
      summary: Tools for building JupyterLite sites (with all)
      license: BSD-3-Clause
      license_file:
        - LICENSE
        - third-party-licenses.json
      homepage: https://github.com/jupyterlite/jupyterlite
      documentation: https://jupyterlite.readthedocs.io

about:
  summary: Tools for building JupyterLite sites
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - third-party-licenses.json
  homepage: https://github.com/jupyterlite/jupyterlite
  documentation: https://jupyterlite.readthedocs.io

extra:
  feedstock-name: jupyterlite-core
  recipe-maintainers:
    - bollwyvl
    - jtpio
    - martinRenou
